version: '3.8'

services:
  database:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: base_db
      MYSQL_DATABASE: base_db
      MYSQL_PASSWORD: root123
