version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      #MYSQL_USER: ''
      # You can use whatever password you like
      #MYSQL_PASSWORD: 'root123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root123'
      MYSQL_ROOT_HOST: '%'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
